# Generated by Django 4.2.7 on 2023-12-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iteams_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteams',
            name='image',
            field=models.TextField(default='https://anycubic.biz/assets/images/products/29896/3d-printer-elegoo-neptune-3-max-1.webp'),
            preserve_default=False,
        ),
    ]
