# Generated by Django 5.0 on 2023-12-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iteams_app', '0002_iteams_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteams',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
